[package]
name = "rbrinfo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-rbrinfo"

[[bin]]
name = "rbrinfo"

[dependencies]
cargo_metadata = "0.18.1"
log = "0.4.21"
serde_json = "1.0.116"

[profile.release]
lto = true
